#singa1
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory_lambda_0_a_0_alpha_0_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory-0.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_2_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory_lambda_2_a_0_alpha_0_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory-16.log

python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_0_a_0_alpha_1_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory_lambda_0_a_0_alpha_1_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory-1.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_2_a_0_alpha_1_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory_lambda_2_a_0_alpha_1_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory-17.log


# slave1
python train.py resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory-baseline-0.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_0_a_0_alpha_2_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory_lambda_0_a_0_alpha_2_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory-2.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_2_a_0_alpha_2_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory_lambda_2_a_0_alpha_2_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory-18.log

python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_0_a_0_alpha_3_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory_lambda_0_a_0_alpha_3_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory-3.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_2_a_0_alpha_3_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory_lambda_2_a_0_alpha_3_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory-19.log

python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_0_a_1_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory_lambda_0_a_1_alpha_0_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory-4.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_2_a_1_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory_lambda_2_a_1_alpha_0_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory-20.log


# slave3
python train.py resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory-baseline-1.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_0_a_1_alpha_1_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory_lambda_0_a_1_alpha_1_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory-5.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_2_a_1_alpha_1_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory_lambda_2_a_1_alpha_1_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory-21.log

python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_0_a_1_alpha_2_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory_lambda_0_a_1_alpha_2_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory-6.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_2_a_1_alpha_2_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory_lambda_2_a_1_alpha_2_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory-22.log

python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_0_a_1_alpha_3_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory_lambda_0_a_1_alpha_3_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory-7.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_2_a_1_alpha_3_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory_lambda_2_a_1_alpha_3_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory/GMM-DL-tune-three-resnet-alpha-init-origin-large-memory-23.log


