# singa1
python train_gpu_0.py resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-baseline-0.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_0_a_0_alpha_0_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-0.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_0_a_0_alpha_1_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_0_a_0_alpha_1_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-1.log


python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_0_a_0_alpha_2_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_0_a_0_alpha_2_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-2.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_0_a_0_alpha_3_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_0_a_0_alpha_3_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-3.log

python train_gpu_1.py resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-baseline-1.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_0_a_1_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_0_a_1_alpha_0_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-4.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_0_a_1_alpha_1_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_0_a_1_alpha_1_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-5.log

python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_0_a_1_alpha_2_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_0_a_1_alpha_2_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-6.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_0_a_1_alpha_3_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_0_a_1_alpha_3_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-7.log

# slave1
python train_gpu_1.py resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-baseline-1.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_1_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_1_a_0_alpha_0_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-8.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_1_a_0_alpha_1_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_1_a_0_alpha_1_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-9.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_1_a_0_alpha_2_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_1_a_0_alpha_2_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-10.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_1_a_0_alpha_3_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_1_a_0_alpha_3_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-11.log

python train_gpu_2.py resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-baseline-2.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_1_a_1_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_1_a_1_alpha_0_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-12.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_1_a_1_alpha_1_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_1_a_1_alpha_1_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-13.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_1_a_1_alpha_2_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_1_a_1_alpha_2_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-14.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_1_a_1_alpha_3_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_1_a_1_alpha_3_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-15.log

# slave3
python train_gpu_0.py resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-baseline-0.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_2_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_2_a_0_alpha_0_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-16.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_2_a_0_alpha_1_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_2_a_0_alpha_1_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-17.log

python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_2_a_0_alpha_2_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_2_a_0_alpha_2_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-18.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_2_a_0_alpha_3_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_2_a_0_alpha_3_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-19.log

python train_gpu_1.py resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-baseline-1.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_2_a_1_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_2_a_1_alpha_0_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-20.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_2_a_1_alpha_1_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_2_a_1_alpha_1_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-21.log

python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_2_a_1_alpha_2_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_2_a_1_alpha_2_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-22.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-12-resnet-alpha-init/hyperparams/lambda_2_a_1_alpha_3_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1_lambda_2_a_1_alpha_3_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1/GMM-DL-tune-three-resnet-alpha-init-olm-last-try-1-23.log


