./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 1 12 693
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON.py 0 12 693
