./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_NLAYERS_PEARSON_3_GPU_0.py 0 12 1711
