./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_result.py 1 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_result.py 0 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON_result.py 1 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON_result.py 0 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_result.py 1 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_result.py 0 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON_result.py 1 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON_result.py 0 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_result.py 1 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_result.py 0 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON_result.py 1 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON_result.py 0 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_result.py 1 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_result.py 0 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON_result.py 1 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON_result.py 0 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_result.py 1 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_result.py 0 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON_result.py 1 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON_result.py 0 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_PEARSON_3.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_result.py 1 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_result.py 0 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON_result.py 1 12 1277
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON_result.py 0 12 1277
