./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_mlp_GPU_OneSrc.py
