./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 1 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 0 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 1 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 0 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 1 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 0 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 1 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 0 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 1 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 0 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 1 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 0 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 1 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 0 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 1 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 0 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 1 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 0 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 1 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 0 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 1 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 0 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 1 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_2SRC_ARBI.py 0 12 1711
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 1 12 1253
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_1SRC_ARBI.py 0 12 1253
