./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_60_10.conf 2>&1 | tee /data/zhaojing/redirect-singa1/60_10
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_60_15.conf 2>&1 | tee /data/zhaojing/redirect-singa1/60_15
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_60_30.conf 2>&1 | tee /data/zhaojing/redirect-singa1/60_30
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_60_45.conf 2>&1 | tee /data/zhaojing/redirect-singa1/60_45
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_60_60.conf 2>&1 | tee /data/zhaojing/redirect-singa1/60_60
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_66_10.conf 2>&1 | tee /data/zhaojing/redirect-singa1/66_10
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_66_17.conf 2>&1 | tee /data/zhaojing/redirect-singa1/66_17
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_66_33.conf 2>&1 | tee /data/zhaojing/redirect-singa1/66_33
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_66_50.conf 2>&1 | tee /data/zhaojing/redirect-singa1/66_50
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_66_66.conf 2>&1 | tee /data/zhaojing/redirect-singa1/66_66
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_140_10.conf 2>&1 | tee /data/zhaojing/redirect-singa1/140_10
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_140_70.conf 2>&1 | tee /data/zhaojing/redirect-singa1/140_70
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_140_35.conf 2>&1 | tee /data/zhaojing/redirect-singa1/140_35
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_140_105.conf 2>&1 | tee /data/zhaojing/redirect-singa1/140_105
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_140_140.conf 2>&1 | tee /data/zhaojing/redirect-singa1/140_140
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_20_10.conf 2>&1 | tee /data/zhaojing/redirect-singa1/20_10
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_20_15.conf 2>&1 | tee /data/zhaojing/redirect-singa1/20_15
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_20_20.conf 2>&1 | tee /data/zhaojing/redirect-singa1/20_20
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_20_5.conf 2>&1 | tee /data/zhaojing/redirect-singa1/20_5
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_60_10.conf 2>&1 | tee /data/zhaojing/redirect-singa1/60_10_1
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_60_15.conf 2>&1 | tee /data/zhaojing/redirect-singa1/60_15_1
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_60_30.conf 2>&1 | tee /data/zhaojing/redirect-singa1/60_30_1
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_60_45.conf 2>&1 | tee /data/zhaojing/redirect-singa1/60_45_1
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_60_60.conf 2>&1 | tee /data/zhaojing/redirect-singa1/60_60_1
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_66_10.conf 2>&1 | tee /data/zhaojing/redirect-singa1/66_10_1
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_66_17.conf 2>&1 | tee /data/zhaojing/redirect-singa1/66_17_1
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_66_33.conf 2>&1 | tee /data/zhaojing/redirect-singa1/66_33_1
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_66_50.conf 2>&1 | tee /data/zhaojing/redirect-singa1/66_50_1
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_66_66.conf 2>&1 | tee /data/zhaojing/redirect-singa1/66_66_1
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_140_10.conf 2>&1 | tee /data/zhaojing/redirect-singa1/140_10_1
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_140_70.conf 2>&1 | tee /data/zhaojing/redirect-singa1/140_70_1
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_140_35.conf 2>&1 | tee /data/zhaojing/redirect-singa1/140_35_1
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_140_105.conf 2>&1 | tee /data/zhaojing/redirect-singa1/140_105_1
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_140_140.conf 2>&1 | tee /data/zhaojing/redirect-singa1/140_140_1
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_20_10.conf 2>&1 | tee /data/zhaojing/redirect-singa1/20_10_1
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_20_15.conf 2>&1 | tee /data/zhaojing/redirect-singa1/20_15_1
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_20_20.conf 2>&1 | tee /data/zhaojing/redirect-singa1/20_20_1
./bin/singa-run.sh -conf examples/CMSHF-CNN-MLP/tune-param/NUH_DS_ALL_COND_cudnn_tune_20_5.conf 2>&1 | tee /data/zhaojing/redirect-singa1/20_5_1
