./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 0 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_KB.py 1 24 153
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_1SRC_PEARSON.py 1 24 153
