./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_mlp_1SRC.py
