./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_KB.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 1 24 338
./bin/singa-run.sh -exec tool/python/examples/CMS_cudnn_2LAYERS_PEARSON.py 0 24 338
