./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_BINCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_1
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_COUNTCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_2
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_PEARSON.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_3
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_BINCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_4
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_COUNTCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_5
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_PEARSON.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_6
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_BINCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_7
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_COUNTCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_8
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_PEARSON.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_9
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_BINCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_10
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_COUNTCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_11
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_PEARSON.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_12
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_BINCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_13
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_COUNTCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_14
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_PEARSON.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_15
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_BINCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_16
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_COUNTCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_17
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_PEARSON.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_18
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_BINCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_19
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_COUNTCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_20
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_PEARSON.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_21
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_BINCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_22
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_COUNTCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_23
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_PEARSON.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_24
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_BINCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_25
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_COUNTCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_26
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_PEARSON.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_27
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_BINCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_28
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_COUNTCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_29
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_PEARSON.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_30
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_BINCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_31
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_COUNTCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_32
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_PEARSON.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_33
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_BINCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_34
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_COUNTCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_35
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_PEARSON.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_CLUSTER_36
