./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_0
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_1
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_2
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_3
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_4
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_5
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_6
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_7
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_8
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_9
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_10
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_11
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_12
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_13
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_14
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_15
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_16
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_17
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_18
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_19
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_20
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_21
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_22
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_23
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_24
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_25
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_26
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_27
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_28
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_29
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_30
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_31
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_32
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_33
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_34
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_35
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_36
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_37
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_38
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0_ARBI.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_ARBI_39
