./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_0
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_1
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_2
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_3
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_4
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_5
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_6
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_7
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_8
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_9
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_10
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_11
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_12
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_13
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_14
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_15
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_16
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_17
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_18
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_19
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_20
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_21
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_22
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_23
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_24
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_25
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_26
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_27
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_28
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_29
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_30
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_31
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_32
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_33
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_34
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_35
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_36
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_37
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_38
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_0.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU0_39
