./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_BINCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_1
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_COUNTCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_2
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_3
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_BINCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_4
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_COUNTCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_5
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_6
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_BINCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_7
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_COUNTCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_8
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_9
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_BINCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_10
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_COUNTCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_11
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_12
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_BINCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_13
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_COUNTCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_14
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_15
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_BINCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_16
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_COUNTCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_17
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_18
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_BINCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_19
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_COUNTCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_20
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_21
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_BINCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_22
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_COUNTCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_23
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_24
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_BINCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_25
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_COUNTCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_26
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_27
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_BINCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_28
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_COUNTCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_29
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_30
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_BINCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_31
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_COUNTCLUSTER.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_32
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON.py 1 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_33
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_BINCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_34
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_COUNTCLUSTER.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_35
./bin/singa-run.sh -exec tool/python/examples/NUH_DS_ALL_COND_cudnn_tune_init_1_PEARSON.py 0 12 1277 > /data/zhaojing/redirect-singa1/py_SINGA1_GPU_1CLUSTER_36
