# singa1
python gm_prior_train.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/8-23/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two_lambda_0_a_0_alpha_0_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two-0.log
python gm_prior_train.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/8-23/hyperparams/lambda_0_a_0_alpha_0_b_1.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two_lambda_0_a_0_alpha_0_b_1_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two-1.log
python gm_prior_train.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/8-23/hyperparams/lambda_0_a_0_alpha_0_b_2.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two_lambda_0_a_0_alpha_0_b_2_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two-2.log
python gm_prior_train.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/8-23/hyperparams/lambda_0_a_0_alpha_1_b_0.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two_lambda_0_a_0_alpha_1_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two-3.log
python gm_prior_train.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/8-23/hyperparams/lambda_0_a_0_alpha_1_b_1.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two_lambda_0_a_0_alpha_1_b_1_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two-4.log
python gm_prior_train.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/8-23/hyperparams/lambda_0_a_0_alpha_1_b_2.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two_lambda_0_a_0_alpha_1_b_2_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two-5.log
python gm_prior_train.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/8-23/hyperparams/lambda_1_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two_lambda_1_a_0_alpha_0_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two-6.log
python gm_prior_train.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/8-23/hyperparams/lambda_1_a_0_alpha_0_b_1.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two_lambda_1_a_0_alpha_0_b_1_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two-7.log
# singa2
python gm_prior_train.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/8-23/hyperparams/lambda_1_a_0_alpha_0_b_2.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two_lambda_1_a_0_alpha_0_b_2_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two-8.log
python gm_prior_train.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/8-23/hyperparams/lambda_1_a_0_alpha_1_b_0.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two_lambda_1_a_0_alpha_1_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two-9.log
python gm_prior_train.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/8-23/hyperparams/lambda_1_a_0_alpha_1_b_1.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two_lambda_1_a_0_alpha_1_b_1_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two-10.log
python gm_prior_train.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/8-23/hyperparams/lambda_1_a_0_alpha_1_b_2.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two_lambda_1_a_0_alpha_1_b_2_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two-11.log
python gm_prior_train.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/8-23/hyperparams/lambda_2_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two_lambda_2_a_0_alpha_0_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two-12.log
python gm_prior_train.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/8-23/hyperparams/lambda_2_a_0_alpha_0_b_1.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two_lambda_2_a_0_alpha_0_b_1_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two-13.log
python gm_prior_train.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/8-23/hyperparams/lambda_2_a_0_alpha_0_b_2.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two_lambda_2_a_0_alpha_0_b_2_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two-14.log
python gm_prior_train.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/8-23/hyperparams/lambda_2_a_0_alpha_1_b_0.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two_lambda_2_a_0_alpha_1_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two-15.log
python gm_prior_train.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/8-23/hyperparams/lambda_2_a_0_alpha_1_b_1.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two_lambda_2_a_0_alpha_1_b_1_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two-16.log
#slave1
python gm_prior_train.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/8-23/hyperparams/lambda_2_a_0_alpha_1_b_2.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two_lambda_2_a_0_alpha_1_b_2_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-two-17.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/8-23/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four_lambda_0_a_0_alpha_0_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four-0.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/8-23/hyperparams/lambda_0_a_0_alpha_0_b_1.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four_lambda_0_a_0_alpha_0_b_1_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four-1.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/8-23/hyperparams/lambda_0_a_0_alpha_0_b_2.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four_lambda_0_a_0_alpha_0_b_2_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four-2.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/8-23/hyperparams/lambda_0_a_0_alpha_1_b_0.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four_lambda_0_a_0_alpha_1_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four-3.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/8-23/hyperparams/lambda_0_a_0_alpha_1_b_1.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four_lambda_0_a_0_alpha_1_b_1_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four-4.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/8-23/hyperparams/lambda_0_a_0_alpha_1_b_2.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four_lambda_0_a_0_alpha_1_b_2_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four-5.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/8-23/hyperparams/lambda_1_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four_lambda_1_a_0_alpha_0_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four-6.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/8-23/hyperparams/lambda_1_a_0_alpha_0_b_1.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four_lambda_1_a_0_alpha_0_b_1_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four-7.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/8-23/hyperparams/lambda_1_a_0_alpha_0_b_2.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four_lambda_1_a_0_alpha_0_b_2_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four-8.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/8-23/hyperparams/lambda_1_a_0_alpha_1_b_0.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four_lambda_1_a_0_alpha_1_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four-9.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/8-23/hyperparams/lambda_1_a_0_alpha_1_b_1.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four_lambda_1_a_0_alpha_1_b_1_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four-10.log
# slave2
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/8-23/hyperparams/lambda_1_a_0_alpha_1_b_2.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four_lambda_1_a_0_alpha_1_b_2_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four-11.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/8-23/hyperparams/lambda_2_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four_lambda_2_a_0_alpha_0_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four-12.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/8-23/hyperparams/lambda_2_a_0_alpha_0_b_1.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four_lambda_2_a_0_alpha_0_b_1_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four-13.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/8-23/hyperparams/lambda_2_a_0_alpha_0_b_2.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four_lambda_2_a_0_alpha_0_b_2_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four-14.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/8-23/hyperparams/lambda_2_a_0_alpha_1_b_0.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four_lambda_2_a_0_alpha_1_b_0_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four-15.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/8-23/hyperparams/lambda_2_a_0_alpha_1_b_1.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four_lambda_2_a_0_alpha_1_b_1_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four-16.log
python gm_prior_train.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/8-23/hyperparams/lambda_2_a_0_alpha_1_b_2.csv -resultpath /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four_lambda_2_a_0_alpha_1_b_2_result.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0823/GMM-DL-four/GMM-DL-four-gmnum-four-17.log