python gm_prior_train_no_data_augment_optimal_for_gm_num.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one_result_0.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one-0.log
python gm_prior_train_no_data_augment_optimal_for_gm_num.py -maxepoch 10 -gmnum 3 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one_result_1.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one-1.log
python gm_prior_train_no_data_augment_optimal_for_gm_num.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one_result_2.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one-2.log
python gm_prior_train_no_data_augment_optimal_for_gm_num.py -maxepoch 10 -gmnum 5 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one_result_3.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one-3.log
python gm_prior_train_no_data_augment_optimal_for_gm_num.py -maxepoch 10 -gmnum 6 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one_result_4.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one-4.log
python gm_prior_train_no_data_augment_optimal_for_gm_num.py -maxepoch 10 -gmnum 8 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one_result_5.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one-5.log
python gm_prior_train_no_data_augment_optimal_for_gm_num.py -maxepoch 10 -gmnum 10 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one_result_6.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one-6.log
python gm_prior_train_no_data_augment_optimal_for_gm_num.py -maxepoch 10 -gmnum 16 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one_result_7.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one-7.log


python gm_prior_train_optimal_for_gm_num.py.py -maxepoch 10 -gmnum 2 -gmuptfreq 100 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one_result_8.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one-8.log
python gm_prior_train_optimal_for_gm_num.py.py -maxepoch 10 -gmnum 3 -gmuptfreq 100 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one_result_9.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one-9.log
python gm_prior_train_optimal_for_gm_num.py.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one_result_10.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one-10.log
python gm_prior_train_optimal_for_gm_num.py.py -maxepoch 10 -gmnum 5 -gmuptfreq 100 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one_result_11.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one-11.log
python gm_prior_train_optimal_for_gm_num.py.py -maxepoch 10 -gmnum 6 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one_result_12.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one-12.log
python gm_prior_train_optimal_for_gm_num.py.py -maxepoch 10 -gmnum 8 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one_result_13.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one-13.log
python gm_prior_train_optimal_for_gm_num.py.py -maxepoch 10 -gmnum 10 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one_result_14.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one-14.log
python gm_prior_train_optimal_for_gm_num.py.py -maxepoch 10 -gmnum 16 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one_result_15.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one-15.log

python train_no_regu.py resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one-16.log
python train_no_data_augment_no_regu.py alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-one/GMM-DL-tune-one-17.log