python train_gpu_0.py resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-baseline-1.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 200 -paramuptfreq 200 -gpuid 0 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-12.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-12.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 100 -gpuid 0 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-13.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-13.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 50 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-14.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-14.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 20 -paramuptfreq 20 -gpuid 0 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-15.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-15.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 10 -paramuptfreq 10 -gpuid 0 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-16.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-16.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 5 -paramuptfreq 5 -gpuid 0 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-17.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-17.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 2 -paramuptfreq 2 -gpuid 0 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-18.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-18.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 1 -paramuptfreq 1 -gpuid 0 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-19.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-19.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 1000 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-20.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-20.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 500 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-21.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-21.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 200 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-22.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-22.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 0 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-23.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-23.log