python train_no_data_augment_gpu_1.py alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-baseline-0.log
python train_no_data_augment_gpu_1.py alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-baseline-0.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 200 -paramuptfreq 200 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-0.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-0.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 100 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-1.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-1.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 50 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-2.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-2.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 20 -paramuptfreq 20 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-3.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-3.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 10 -paramuptfreq 10 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-4.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-4.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 5 -paramuptfreq 5 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-5.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-5.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 2 -paramuptfreq 2 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-6.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-6.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 1 -paramuptfreq 1 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-7.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-7.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 1000 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-8.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-8.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 500 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-9.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-9.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 200 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-10.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-10.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-result-11.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two-olmemory/GMM-DL-tune-two-olmemory-11.log