ssh logbase-b06 /home/singa/zhaojing/NUH-singa/incubator-singa/script/kill-process.sh
echo "ssh logbase-b06"
ssh logbase-b07 /home/singa/zhaojing/NUH-singa/incubator-singa/script/kill-process.sh
echo "ssh logbase-b07"
ssh logbase-b08 /home/singa/zhaojing/NUH-singa/incubator-singa/script/kill-process.sh
echo "ssh logbase-b08"
ssh logbase-b09 /home/singa/zhaojing/NUH-singa/incubator-singa/script/kill-process.sh
echo "ssh logbase-b09"
ssh logbase-b10 /home/singa/zhaojing/NUH-singa/incubator-singa/script/kill-process.sh
echo "ssh logbase-b10"
ssh logbase-b11 /home/singa/zhaojing/NUH-singa/incubator-singa/script/kill-process.sh
echo "ssh logbase-b11"
ssh logbase-b12 /home/singa/zhaojing/NUH-singa/incubator-singa/script/kill-process.sh
echo "ssh logbase-b12"
ssh logbase-b13 /home/singa/zhaojing/NUH-singa/incubator-singa/script/kill-process.sh
echo "ssh logbase-b13"
ssh logbase-b14 /home/singa/zhaojing/NUH-singa/incubator-singa/script/kill-process.sh
echo "ssh logbase-b14"
ssh logbase-b15 /home/singa/zhaojing/NUH-singa/incubator-singa/script/kill-process.sh
echo "ssh logbase-b15"
ssh logbase-b16 /home/singa/zhaojing/NUH-singa/incubator-singa/script/kill-process.sh
echo "ssh logbase-b16"
ssh logbase-b17 /home/singa/zhaojing/NUH-singa/incubator-singa/script/kill-process.sh
echo "ssh logbase-b17"
