ssh logbase-a22 nohup python /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/marbleTests_zj_argu.py 100 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample2/NUHALLCOND_subs_splittrain_2.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample2/NUHALLCOND_vals_binary_splittrain_2.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv 150 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample2/NUHALLCOND_subs_splittest_2.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample2/NUHALLCOND_vals_binary_splittest_2.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_train_S2_100_1.txt /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_test_S2_100_1.txt > /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/redirect_S2_100_1 2>&1 &
echo "ssh logbase-a22"
ssh logbase-a23 nohup python /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/marbleTests_zj_argu.py 100 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample3/NUHALLCOND_subs_splittrain_3.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample3/NUHALLCOND_vals_binary_splittrain_3.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv 150 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample3/NUHALLCOND_subs_splittest_3.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample3/NUHALLCOND_vals_binary_splittest_3.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_train_S3_100_2.txt /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_test_S3_100_2.txt > /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/redirect_S3_100_2 2>&1 &
echo "ssh logbase-a23"
ssh logbase-a26 nohup python /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/marbleTests_zj_argu.py 100 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample3/NUHALLCOND_subs_splittrain_3.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample3/NUHALLCOND_vals_binary_splittrain_3.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv 150 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample3/NUHALLCOND_subs_splittest_3.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample3/NUHALLCOND_vals_binary_splittest_3.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_train_S3_100_3.txt /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_test_S3_100_3.txt > /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/redirect_S3_100_3 2>&1 &
echo "ssh logbase-a26"
ssh logbase-a27 nohup python /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/marbleTests_zj_argu.py 100 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample4/NUHALLCOND_subs_splittrain_4.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample4/NUHALLCOND_vals_binary_splittrain_4.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv 150 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample4/NUHALLCOND_subs_splittest_4.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample4/NUHALLCOND_vals_binary_splittest_4.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_train_S4_100_2.txt /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_test_S4_100_2.txt > /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/redirect_S4_100_2 2>&1 &
echo "ssh logbase-a27"
ssh logbase-a28 nohup python /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/marbleTests_zj_argu.py 100 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample4/NUHALLCOND_subs_splittrain_4.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample4/NUHALLCOND_vals_binary_splittrain_4.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv 150 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample4/NUHALLCOND_subs_splittest_4.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample4/NUHALLCOND_vals_binary_splittest_4.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_train_S4_100_3.txt /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_test_S4_100_3.txt > /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/redirect_S4_100_3 2>&1 &
echo "ssh logbase-a28"
ssh logbase-a31 nohup python /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/marbleTests_zj_argu.py 100 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample5/NUHALLCOND_subs_splittrain_5.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample5/NUHALLCOND_vals_binary_splittrain_5.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv 150 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample5/NUHALLCOND_subs_splittest_5.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample5/NUHALLCOND_vals_binary_splittest_5.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_train_S5_100_2.txt /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_test_S5_100_2.txt > /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/redirect_S5_100_2 2>&1 &
echo "ssh logbase-a31"
ssh logbase-a32 nohup python /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/marbleTests_zj_argu.py 100 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample5/NUHALLCOND_subs_splittrain_5.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample5/NUHALLCOND_vals_binary_splittrain_5.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv 150 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample5/NUHALLCOND_subs_splittest_5.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample5/NUHALLCOND_vals_binary_splittest_5.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_train_S5_100_3.txt /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_test_S5_100_3.txt > /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/redirect_S5_100_3 2>&1 &
echo "ssh logbase-a32"
ssh logbase-a33 nohup python /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/marbleTests_zj_argu.py 100 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample6/NUHALLCOND_subs_splittrain_6.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample6/NUHALLCOND_vals_binary_splittrain_6.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv 150 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample6/NUHALLCOND_subs_splittest_6.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample6/NUHALLCOND_vals_binary_splittest_6.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_train_S6_100_2.txt /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_test_S6_100_2.txt > /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/redirect_S6_100_2 2>&1 &
echo "ssh logbase-a33"
ssh logbase-a34 nohup python /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/marbleTests_zj_argu.py 100 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample6/NUHALLCOND_subs_splittrain_6.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample6/NUHALLCOND_vals_binary_splittrain_6.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv 150 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample6/NUHALLCOND_subs_splittest_6.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample6/NUHALLCOND_vals_binary_splittest_6.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_train_S6_100_3.txt /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_test_S6_100_3.txt > /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/redirect_S6_100_3 2>&1 &
echo "ssh logbase-a34"
ssh logbase-a35 nohup python /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/marbleTests_zj_argu.py 100 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample7/NUHALLCOND_subs_splittrain_7.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample7/NUHALLCOND_vals_binary_splittrain_7.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv 150 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample7/NUHALLCOND_subs_splittest_7.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample7/NUHALLCOND_vals_binary_splittest_7.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_train_S7_100_2.txt /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_test_S7_100_2.txt > /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/redirect_S7_100_2 2>&1 &
echo "ssh logbase-a35"
ssh logbase-b05 nohup python /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/marbleTests_zj_argu.py 100 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample7/NUHALLCOND_subs_splittrain_7.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample7/NUHALLCOND_vals_binary_splittrain_7.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv 150 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample7/NUHALLCOND_subs_splittest_7.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample7/NUHALLCOND_vals_binary_splittest_7.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_train_S7_100_3.txt /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_test_S7_100_3.txt > /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/redirect_S7_100_3 2>&1 &
echo "ssh logbase-b05"
ssh logbase-b06 nohup python /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/marbleTests_zj_argu.py 100 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample8/NUHALLCOND_subs_splittrain_8.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample8/NUHALLCOND_vals_binary_splittrain_8.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv 150 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample8/NUHALLCOND_subs_splittest_8.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample8/NUHALLCOND_vals_binary_splittest_8.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_train_S8_100_1.txt /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_test_S8_100_1.txt > /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/redirect_S8_100_1 2>&1 &
echo "ssh logbase-b06"
ssh logbase-b23 nohup python /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/marbleTests_zj_argu.py 100 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample8/NUHALLCOND_subs_splittrain_8.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample8/NUHALLCOND_vals_binary_splittrain_8.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv 150 /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample8/NUHALLCOND_subs_splittest_8.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/subsample8/NUHALLCOND_vals_binary_splittest_8.csv /data/zhaojing/cnn/MARBLE/PEARSON-3/siz.csv /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_train_S8_100_2.txt /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/membership_test_S8_100_2.txt > /home/singa/zhaojing/NUH-singa/incubator-singa/examples/data-process/python/Marble-code/NUHALLCOND-PEARSON-3-membership/redirect_S8_100_2 2>&1 &
echo "ssh logbase-b23"
