python train_no_data_augment_gpu_1.py alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-baseline-0.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 125 -paramuptfreq 125 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-result-0.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-0.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 100 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-result-1.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-1.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 75 -paramuptfreq 75 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-result-2.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-2.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 50 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-result-3.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-3.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 25 -paramuptfreq 25 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-result-4.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-4.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-result-5.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-5.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 200 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-result-6.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-6.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 400 -paramuptfreq 50 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-result-7.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-7.log
python gm_prior_train_no_data_augment_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 1 -paramuptfreq 1 -gpuid 1 -hyperparampath script_generator/9-10-alexnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-result-8.txt alexnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-8.log