python train_gpu_2.py resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-baseline-1.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 125 -paramuptfreq 125 -gpuid 2 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-result-9.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-9.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 100 -gpuid 2 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-result-10.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-10.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 75 -paramuptfreq 75 -gpuid 2 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-result-11.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-11.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 50 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-result-12.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-12.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 25 -paramuptfreq 25 -gpuid 2 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-result-13.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-13.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 100 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-result-14.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-14.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 200 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-result-15.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-15.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 400 -paramuptfreq 50 -gpuid 2 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-result-16.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-16.log
python gm_prior_train_optimal_for_freq.py -maxepoch 10 -gmnum 4 -gmuptfreq 1 -paramuptfreq 1 -gpuid 2 -hyperparampath script_generator/9-8-resnet-new-scale/hyperparams/lambda_0_a_0_alpha_0_b_0.csv -resultpath /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-result-17.txt resnet cifar-10-batches-py/ | tee -a /data/zhaojing/regularization/log0912/GMM-DL-tune-two/GMM-DL-tune-two-17.log